### ISSUE TITLE
Neorocks uses different version of nixpkgs

### ISSUE THREAD

**Issue by stelcodes** [MrcJkb/telescope-manix#12]
Wow, seriously awesome plugin! Thanks so much.

I noticed that your flake's `neorocks` inputs pulls in `nixpkgs` but it isn't marked to follow your `nixpkgs` version. Was that purposeful?

**Comment by mrcjkb** [comment]
Thanks for the nice words 😊

`neorocks` builds and caches neovim-nightly (among other things) in a separate CI, and its flake.lock is updated nightly.

I'm not sure, but wouldn't following this flake's nixpkgs mean I have to rebuild?
